// Do not edit this file manually
import { parseBlockCredentials, parseBlockSchema } from "@typebot.io/forge";
import { smartflowBlock } from ".";
import { auth } from "./auth";

export const smartflowBlockSchema = parseBlockSchema(smartflowBlock);
export const smartflowCredentialsSchema = parseBlockCredentials(
  smartflowBlock.id,
  auth.schema,
);
